# Defines object locations as [x, y, theta]
#Define your waypoints based on occupancy grid
location1: [0.0, 0.0, -2.356]
location2: [1.0, 1.0, 0.785]
location3: [1.0, -0.5, 1.571]
location4: [0.0, 0.0, -2.356]
